### ISSUE TITLE
We must use git-flow for versioning and development

### ISSUE THREAD

**Issue by vilusa** [ilkbyte/api-ruby#6]
I think git-flow is the best tool for feature development and new release publishing.
When I look at it now, there is only the main branch in the repo. With Git flow, I think we can better manage the development process as two branches as develop and master. You can review the following resource for the case studies.

[Git Flow Cheatsheet](https://danielkummer.github.io/git-flow-cheatsheet/)

**Comment by vilusa** [comment]
Hi @osmanmakal, I made some updates about gem so can you activate the develop branch in the repo?

**Comment by osmanmakal** [comment]
Hello @vilusa, Thank you. We created a new branch for develop
